sonar.projectKey=bookstore_api-gateway
sonar.organization=your-sonarcloud-org
sonar.projectName=BookStore api-gateway
sonar.sources=src
sonar.exclusions=node_modules/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
