sonar.projectKey=bookstore_book-service
sonar.organization=dinethrashmikaheshan
sonar.projectName=BookStore book-service
sonar.sources=src
sonar.exclusions=node_modules/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
